### ISSUE TITLE
Incorporate skins data

### ISSUE THREAD

**Issue by ericgio** [ericgio/weekday-golf#15]

**Comment by makinde** [comment]
Implementation ideas:
- add a “(s)” after people’s names on the spreadsheet if they participated in skins, and then getAllData can pick that up and add a “skinsPlayers” field to the round object.
- (UI, I’m prob wrong here) have some symbol show up beside scores on the round list page saying if that score won a (or multiple) skins. Maybe a dot or something? Then add a column to the right of round total for showing the total number of skins won (perhaps with a a +/- in parens denoting the relative performance to others)

**Comment by fzamore** [comment]
For the skins symbol, I vote for ($), (🏦), (💵), or something like that.

**Comment by makinde** [comment]
next up for me.
