### ISSUE TITLE
Use CSS modules

### ISSUE THREAD

**Issue by makinde** [ericgio/weekday-golf#17]
I think CSS modules are the default, built in way for doing component level CSS in nextJS. https://nextjs.org/docs/basic-features/built-in-css-support#adding-component-level-css Prob not a huge difference either way. Upside of switching is to be more in line with the default/require fewer external packages, and also avoid conflicting class names (which is a tiny chance of happening at this scale). @zeit/next-sass Also doesn’t seem to be updated anymore.

Also not sure if it matter, but CSS is currently flaky for me in dev. Sometimes it loads, other times not.

**Comment by ericgio** [comment]
This would be relatively easy, except we're using global classnames as a feature in a lot of our tables. We'd need to think about how to re-use styles across components.
