### ISSUE TITLE
Add static analysis to check out what's going in the bundle

### ISSUE THREAD

**Issue by makinde** [ericgio/weekday-golf#20]
https://flaviocopes.com/nextjs-analyze-app-bundle/

**Comment by ericgio** [comment]
Any insights from this?

**Comment by makinde** [comment]
All of lodash was making it into the bundle. I updated the imports to allow most of it to be left out.

I can’t remember if all of d3 is being brought in. I think it was from one of my times running it. That may have been the largest non-react/next part of the bundle now.

Bundle size is now just below next’s cutoff between green and yellow. 2 weeks ago it was at red. Note, the colors can be seen by just running `yarn run build`.

Check it out. If you run `yarn run analyze`, it’ll open an interactive view of the server and client bundles in your browser automatically.
